before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'

    binary: '{{ .ProjectName }}'
    main: main.go

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  algorithm: sha256