# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/build/
project_name: '{{ .ProjectName }}'
gomod:
  proxy: false
builds:
  - env: [CGO_ENABLED=0]
    binary: '{{ .ProjectName }}'
    main: ./
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'