name: 🎉 Release Binary

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
    
      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version: 1.19
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        name: Run GoReleaser
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}